# Generated by Django 5.0 on 2023-12-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfterMarketDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('price', models.TextField()),
                ('bids', models.TextField()),
                ('ending', models.TextField()),
                ('majestic_tf', models.TextField()),
                ('majestic_mdp', models.TextField()),
                ('majestic_cf', models.TextField()),
                ('majestic_ttf', models.TextField()),
                ('semrush_srust', models.TextField()),
                ('semrush_srusk', models.TextField()),
                ('semrush_srusr', models.TextField()),
                ('semrush_srusc', models.TextField()),
                ('majestic_bl', models.TextField()),
                ('wby', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
