# Generated by Django 5.0 on 2023-12-16 06:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainArticleGenetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article', tinymce.models.HTMLField()),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
